### ISSUE TITLE
Cross-build of some packages not yet correct

### ISSUE THREAD

**Issue by jan-kiszka** [siemens/meta-coral#4]
Looks like cross-building of some python packages with native parts, e.g. pasta, is not yet working as it should. Rather then using the pre-installed `crossbuild-essential`, `build-essential` is installed. Furthermore, `linux-libc-dev:<target>` gets pulled while `linux-libc-dev-<target>-cross` should be used. This causes massive problems with the current sharing of buildchroot-host in Isar (see e.g. https://github.com/siemens/meta-iot2050/runs/4957053783?check_suite_focus=true).

**Comment by fmoessbauer** [comment]
The building of the python packages should be correct. Here, we strictly follow the [debian guide](https://wiki.debian.org/CrossBuildPackagingGuidelines#Python_extensions).

However, it looks like we overwrite the `DEB_BUILD_PROFILE` in the linux-custom recipe, because we only added patch-1 of the `DEB_BUILD_PROFILES` [series](https://groups.google.com/g/isar-users/c/WjNt73eVvS0/m/jmUsd8D2EgAJ) to this layer. Should be fixed in 77f96045e149c1747a54084e264a8ac8e904a129

**Comment by jan-kiszka** [comment]
Looks like - I'm validating this ATM.
